### ISSUE TITLE
Ridiculous Build times for 7.10

### ISSUE THREAD

**Issue by crockeea** [haskell-suite/haskell-src-exts#229] opened 2015-06-19 04:06 UTC
It's quite possible this is a 7.10 performance regression, but I figured this is the logical place to start. 
My build log is here: http://lpaste.net/134779
The build maxed out my 8GiB of memory then proceeded to use all of my swap space, maxed out 4 i7 cores, and took over 7 minutes.

**Comment by osa1** [comment] 2015-07-18 17:18
IIRC haskell-src-exts build times were always ridiculous. Have you compared your results with GHC 7.8, 7.6 etc.? I'm wondering if this a GHC 7.10 regression.

**Comment by crockeea** [comment] 2015-07-18 17:20
I have installed HSE on previous versions of GHC, and don't recall this problem, however I don't have a way to verify that at the moment.

**Comment by pjonsson** [comment] 2015-08-04 14:14
It would be nice to have some more data than "It takes a long time" because it has taken a long time to build since all the deriving clauses were added to the data types. In comparison, the Travis build bots usually take 8-12 minutes to build HSE and run the tests with 7.4/7.6/7.8 so 7 minutes doesn't sound bad at all.

**Comment by crockeea** [comment] 2015-08-05 17:14
I'm not sure what else I can give you besides the -v3 build log above. If you think this build time is reasonable for HSE, then feel free to close.

**Comment by pjonsson** [comment] 2015-08-05 17:36
You can significantly speed up the build by building with `-O0` and `--disable-library-profiling`. If you need the performance from optimization and/or library profiling that doesn't help you though.

Ticket #148 is concerning the slowness of compilation in general along with some analysis of the problem. We don't have any solutions for it though unfortunately, it's a lot of code that needs to be compiled.

I'll close this ticket since the other ticket is alive and kicking.

**Closed by pjonsson** 2015-08-05 17:36 UTC
