### ISSUE TITLE
Indentation handled differently to GHC

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#228] opened 2015-06-13 17:51 UTC
From http://trac.haskell.org/haskell-src-exts/ticket/216 and confirmed to still exist:

The following program works under GHC:

    main = f where
        f = g where
        g = putStrLn "hello world"

But under HSE gives the error `Patch.hs:5:1: Parse error Error message: Parse error: ;`.

**Comment by mpickering** [comment] 2015-07-26 19:21
I dug into this a bit and the problem is in the [lexBOL function](https://github.com/haskell-suite/haskell-src-exts/blob/5313e669d979a755da50667ad1d2d395997e3d91/src/Language/Haskell/Exts/InternalLexer.hs#L484) but I didn't understand enough to quickly find a fix.

**Comment by pjonsson** [comment] 2015-08-05 16:56
Fixed in 907342822387a3a1b34ebc64f3a5d9c6a4425a5d.

**Closed by pjonsson** 2015-08-05 16:56 UTC
